image_optimization.settings:
  type: config_object
  label: 'Image Optimization Settings'
  mapping:
    public_key:
      type: path
      label: 'Public Key'
      description: 'The path to the public file.'
    private_key:
      type: path
      label: 'Private Key'
      description: 'The path to the private file.'
